spring:
  profiles:
    include: secret

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers, beans
  endpoint:
    health:
      show-details: always